---

- name: Update & Uprade Ubuntu System
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_facts["os_family"] == "Debian"

- name: Update & Upgrade RedHat System
  dnf:
    name: '*'
    state: latest
  when: ansible_facts["os_family"] == "RedHat"