---

- name: Print auditd_package value
  debug:
    msg: "auditd_package = {{ auditd_package }}"

- name: Install audit auditd_package
  package:
    name: "{{ auditd_package }}"
    state: present

- name: Enable and start auditd service
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    state: started