---

- name: Disable root login os ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Restart SSH service
  ansible.builtin.systemd:
    name: "{{ ssh_daemon }}"
    state: restarted
  notify: Restart ssh